
{
  "before_script": [
    "sudo apt-get update",
    "sudo apt-get install build-essential software-properties-common -y",
    "sudo apt-get install texinfo libgmp-dev libmpfr-dev libmpc-dev libc6-dev zlib1g-dev g++ -y",
    "uname -a",
    "cat /etc/issue",
    "wget http://www.mpfr.org/mpfr-current/mpfr-3.1.5.tar.gz",
    "mkdir /home/travis/build/zhaibin18/mpfr",
    "tar -zxf mpfr-3.1.5.tar.gz",
    "cd mpfr-3.1.5",
    "./configure --prefix=/home/travis/build/zhaibin18/mpfr && make && make install",
    "cd ~",
    "wget https://ftp.gnu.org/gnu/gmp/gmp-6.1.1.tar.xz",
    "tar -pxf gmp-6.1.1.tar.xz",
    "mkdir /home/travis/build/zhaibin18/gmp",
    "cd gmp-6.1.1",
    "./configure --prefix=/home/travis/build/zhaibin18/gmp && make && make install",
    "cd ~",
    "wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz",
    "mkdir /home/travis/build/zhaibin18/mpc",
    "tar -zxf mpc-1.0.3.tar.gz",
    "cd mpc-1.0.3",
    "./configure --prefix=/home/travis/build/zhaibin18/mpc --with-gmp=/home/travis/build/zhaibin18/gmp --with-mpfr=/home/travis/build/zhaibin18/mpfr && make && make install",
    "cd ~",
    "mkdir /home/travis/build/zhaibin18/isl",
    "wget http://isl.gforge.inria.fr/isl-0.16.tar.gz",
    "tar -zxf isl-0.16.tar.gz",
    "cd isl-0.16",
    "./configure --prefix=/home/travis/build/zhaibin18/isl --with-gmp-prefix=/home/travis/build/zhaibin18/gmp && make && make install",
    "cd ~",
    "wget http://www.netgull.com/gcc/releases/gcc-6.2.0/gcc-6.2.0.tar.gz",
    "mkdir /home/travis/build/zhaibin18/gcc",
    "mkdir /home/travis/build/zhaibin18/gcc6_tmp",
    "mkdir /home/travis/build/zhaibin18/gcc6_src",
    "tar -zxf gcc-6.2.0.tar.gz -C /home/travis/build/zhaibin18/gcc6_src",
    "cd /home/travis/build/zhaibin18/gcc6_tmp",
    "/home/travis/build/zhaibin18/gcc6_src/configure --prefix=/home/travis/build/zhaibin18/gcc --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=mipsel-linux --enable-checking=release --enable-languages=c,c++,go --disable-multilib --with-gmp=/home/travis/build/zhaibin18/gmp --with-mpfr=/home/travis/build/zhaibin18/mpfr --with-mpc=/home/travis/build/zhaibin18/mpc --with-isl=/home/travis/build/zhaibin18/isl",
    "make"
  ],
  "language": "c",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
